services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_unitex
    restart: always
    env_file:
      - ./n8n/.env
    ports:
      - "5678:5678"
    networks:
      - unitex_network

networks:
  unitex_network:
    driver: bridge